---
name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  mypy:
    strategy:
      matrix:
        python_ver:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_ver }}

      - run: |-
          sudo -- apt install --yes -- universal-ctags

      - run: |-
          pip3 install -- codespell
          codespell --skip ./artifacts/helo.yml --skip ./tests/shared/fuzzy.py --ignore-words-list assertIn thirdparty

      - run: |-
          make lint

      - run: |-
          python3 -m coq deps

      - run: |-
          make test
